apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.name" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
data:
  database__connection__password: {{ .Values.ghost.password | b64enc }}