apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost.name" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
data:
  database__connection__host: {{ include "ghost.callNested" (list . "mysql" "mysql.primary.fullname") }}
  url: {{ .Values.ghost.url }}
  NODE_ENV: {{ .Values.ghost.nodeEnv }}
  database__connection__database: {{ .Values.ghost.database }}
  database__connection__user: {{ .Values.ghost.user }}