apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.name" . }}
  {{- with .Values.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
    {{- include "ghost.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "ghost.name" . }}
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "ghost.name" . }}
        {{- include "ghost.selectorLabels" . | nindent 8 }}
      annotations:
        # rollme: {{ randAlphaNum 5 | quote }}
        {{- include "ghost.annotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      serviceAccountName: {{ include "ghost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "ghost.name" . }}
          {{- if .Values.command }}
          command: {{ .Values.command.shell }}
          {{- end }}
          {{- with .Values.command.args }}
          args:
{{ toYaml . | indent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "ghost.image" . }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          {{- if .Values.lifecycle }}
          lifecycle:
{{ toYaml .Values.lifecycle | indent 12 }}
          {{- end }}
          {{- if .Values.extraEnvs }}
          env:
            {{- toYaml .Values.extraEnvs | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "ghost.name" . }}
            - secretRef:
                name: {{ include "ghost.name" . }}
          ports:
            - name: {{ .Values.targetPortName }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.extraInitContainers }}
      initContainers:
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.persistentVolumeClaim.enabled }}
      volumes:
        - name: {{ include "ghost.name" . }}
          persistentVolumeClaim:
            claimName: {{ include "ghost.name" . }}
      {{- end }}