{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost.name" . }}
  labels:
    app: {{ include "ghost.name" . }}
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistentVolumeClaim.accessModes }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
{{- end }}